import test from 'node:test';
import assert from 'node:assert/strict';
import {measureAcoustics,pcmFromWav} from '../lib/acoustics.ts';
function tone(hz:number,seconds=2,amplitude=.3){return Float32Array.from({length:16000*seconds},(_,i)=>amplitude*Math.sin(2*Math.PI*hz*i/16000));}
test('pitch estimates track known signals without treating pitch as emotion',()=>{for(const hz of [80,120,200,320]){const a=measureAcoustics(tone(hz));assert.equal(a.status,'available');assert.ok(Math.abs(a.pitchMedianHz!-hz)<2);assert.ok(a.pitchRangeSemitones!<.2);assert.equal('emotion'in a,false);}});
test('pitch movement and recorded-level variation are separately measured',()=>{let phase=0;const sweep=Float32Array.from({length:48000},(_,i)=>{phase+=2*Math.PI*(120+120*i/48000)/16000;return (.1+.35*i/48000)*Math.sin(phase);});const a=measureAcoustics(sweep);assert.equal(a.status,'available');assert.ok(a.pitchRangeSemitones!>7);assert.ok(a.levelRangeDb!>6);assert.ok(Math.abs(measureAcoustics(tone(200,2,.05)).pitchMedianHz!-200)<2);});
test('silence, clipping, very short and invalid samples do not yield reliable estimates',()=>{for(const sample of [new Float32Array(32000),tone(200,2,2),tone(200,.1),Float32Array.of(NaN)])assert.equal(measureAcoustics(sample).status,'insufficient');});
test('aperiodic noise is not reported as reliable pitched speech',()=>{let seed=42;const noise=Float32Array.from({length:32000},()=>{seed=(1664525*seed+1013904223)>>>0;return (seed/4294967296-.5)*.6;});assert.equal(measureAcoustics(noise).status,'insufficient');});
test('canonical WAV parser rejects misleading header lengths and unsupported rates',()=>{const b=new Uint8Array(48);const v=new DataView(b.buffer);for(const [offset,word] of [[0,'RIFF'],[8,'WAVE'],[12,'fmt '],[36,'data']]as const)for(let i=0;i<word.length;i++)b[offset+i]=word.charCodeAt(i);v.setUint32(4,40,true);v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);v.setUint32(40,4,true);v.setInt16(44,16384,true);assert.equal(pcmFromWav(b)?.[0],.5);v.setUint32(4,99,true);assert.equal(pcmFromWav(b),null);assert.equal(pcmFromWav(new Uint8Array(3)),null);});
