const {chromium}=require(process.env.PLAYWRIGHT_MODULE),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});try{
 const page=await browser.newPage({viewport:{width:390,height:844},permissions:['microphone'],reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.__notifications=0;window.Notification=class {static permission='default';static async requestPermission(){this.permission='granted';return 'granted';}constructor(){window.__notifications++;}close(){}};});
 const step={title:'Open clearly',purpose:'Explain one benefit',goal:'Clear and approachable',sentence:'Our project makes practice personal.',cue:'Emphasize personal.',direction:{emphasis:'personal',pauseAfter:null},challenge:'Introduce the benefit.',successCheck:'Was the main idea clear?',emotion:'confident'};
 const plan={id:'11111111-1111-4111-8111-111111111111',title:'Expo opening',task:'Prepare for the expo',outcome:'Explain the benefit',createdAt:new Date().toISOString(),steps:[step,step,step,step]};const old={...plan,id:'22222222-2222-4222-8222-222222222222',title:'An earlier goal'};
 const first={id:'33333333-3333-4333-8333-333333333333',planId:plan.id,planStep:0,kind:'delivery',input:'audio',source:'gemini',goal:step.goal,transcript:step.sentence,createdAt:new Date().toISOString(),feedback:{summary:'Your point is clear.',strength:'The benefit stands out.',adjustment:'',example:'',nextPrompt:'',observation:null},acoustics:{version:'yin-1',status:'available',duration:3,pitchMedianHz:140,pitchRangeSemitones:4.2,levelRangeDb:8,pitchedSeconds:1.4,clippedPercent:0,contour:[{time:.1,hz:120,db:-20},{time:1,hz:145,db:-22}]}};
 const second={...first,id:'44444444-4444-4444-8444-444444444444',parentId:first.id,reflection:'second',change:{outcome:'closer',summary:'Your emphasis makes the benefit clearer.',beforeQuote:'personal',afterQuote:'personal',reason:'Stronger emphasis.'}};
 const state={introduction:'complete',profile:{name:'A',strengths:'Confidence',workingOn:'Rambling',intention:'Clear and approachable',situations:'',focus:'',coachingStyle:'gentle',voicePreset:'default'},activePlanId:plan.id,learningPlans:[old,plan],returns:[{id:'check',planId:plan.id,dueAt:new Date(Date.now()-1000).toISOString()}],voiceSessions:[],attempts:[first,second],messages:[],scenarios:[],completed:[],discovery:{turns:[]},memory:{status:'off'},capabilities:{mode:'live',gemini:true,speech:true,transcription:true,voices:['default'],database:'local',memory:false}};
 let baselineId,tts=[];const wav=Buffer.alloc(44+3200);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(3200,40);
 await page.route('**/api/**',async r=>{const url=new URL(r.request().url()).pathname;const body=r.request().method()==='POST'&&!url.endsWith('/attempts')?r.request().postDataJSON():null;
  if(url==='/api/state')return r.fulfill({json:state});if(url==='/api/personal-voice')return r.fulfill({json:{status:'ready'}});
  if(url==='/api/learning-plan/select'){state.activePlanId=body.id;return r.fulfill({json:{ok:true}})}
  if(url==='/api/return-check/notified'){state.returns[0].notifiedAt=new Date().toISOString();return r.fulfill({json:{ok:true}})}
  if(url==='/api/return-check/complete'){Object.assign(state.returns[0],body,{completedAt:new Date().toISOString()});return r.fulfill({json:{ok:true}})}
  if(url==='/api/return-check'){state.returns.push({...body,id:'next'});return r.fulfill({json:{ok:true}})}
  if(url==='/api/comparisons/save'){second.savedComparison=body.keep;return r.fulfill({json:{ok:true}})}
  if(url==='/api/speech'||url==='/api/personal-voice/speech'){tts.push(body);return r.fulfill({contentType:'audio/wav',body:wav})}
  if(url.startsWith('/api/audio/'))return r.fulfill({contentType:'audio/wav',body:wav});
  if(url==='/api/attempts'){const req=r.request(),f=await new Response(req.postDataBuffer(),{headers:{'content-type':req.headers()['content-type']}}).formData();assert.equal(f.get('planId'),null);const bytes=Buffer.from(await f.get('audio').arrayBuffer());assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.readUInt32LE(24),16000);const baseline={...first,id:f.get('requestId'),planId:undefined};state.attempts.push(baseline);baselineId=baseline.id;return r.fulfill({json:baseline})}
  if(url==='/api/learning-plan'){assert.equal(body.baselineId,baselineId);const next={...plan,id:body.requestId,title:'Plan from my starting point',task:body.task,baselineId};state.learningPlans.push(next);state.activePlanId=next.id;return r.fulfill({json:next})}
  return r.fulfill({status:404,json:{error:'Not mocked'}});
 });
 await page.goto('http://127.0.0.1:3000');await page.getByRole('heading',{name:'How did it go?'}).waitFor();assert.equal(await page.evaluate(()=>window.__notifications),0);await page.getByRole('button',{name:'Enable browser reminders'}).click();await page.waitForFunction(()=>window.__notifications===1);await page.getByLabel('One moment to remember (optional)').fill('I rushed my follow-up.');await page.getByRole('button',{name:'Some parts worked'}).click();await page.getByRole('heading',{name:'Take this into a real conversation.'}).waitFor();assert.equal(state.returns[0].note,'I rushed my follow-up.');await page.getByRole('button',{name:'Check in tomorrow'}).click();await page.getByRole('status').filter({hasText:'Check-in:'}).waitFor();
 await page.getByRole('list',{name:'Your preparation steps'}).getByRole('button').first().click();await page.getByRole('button',{name:'Resume this practice'}).click();await page.getByRole('tab',{name:'Listen & timing'}).click();await page.getByRole('heading',{name:'Hear how your voice moves.'}).waitFor();await page.getByRole('button',{name:'Keep both recordings for later'}).click();await page.getByRole('button',{name:'Stop keeping this comparison'}).waitFor();assert.equal(second.savedComparison,true);
 await page.getByRole('button',{name:'Hear the coach example'}).click();await page.getByRole('button',{name:'Hear it in my voice'}).click();await page.waitForFunction(()=>document.querySelectorAll('audio').length>=4);assert.equal(tts.length,2);for(const b of tts)assert.deepEqual(b.direction,step.direction);
 await page.getByRole('navigation',{name:'Your saved plans'}).getByRole('button',{name:'An earlier goal'}).click();await page.getByRole('heading',{name:'An earlier goal'}).waitFor();await page.reload();await page.getByRole('heading',{name:'An earlier goal'}).waitFor();
 await page.getByRole('button',{name:'Prepare for a different moment'}).click();await page.getByLabel('Your upcoming conversation or presentation').fill('Prepare for a project introduction');await page.getByRole('button',{name:/Want a plan based on your voice/}).click();await page.getByRole('button',{name:'Record response',exact:true}).click();await page.getByRole('button',{name:/Stop recording/}).waitFor();await page.waitForTimeout(800);await page.getByRole('button',{name:/Stop recording/}).click();await page.getByRole('button',{name:'Use this as my starting point'}).click();await page.getByRole('status').filter({hasText:'Your starting point is ready'}).waitFor();await page.getByRole('button',{name:'Build my practice plan'}).click();await page.getByRole('heading',{name:'Plan from my starting point'}).waitFor();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width)}fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/continuity-desktop.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS continuity UI: notification opt-in, due reflection, tomorrow reminder, acoustic evidence, retained pair, both directed voices, old plan/reload, PCM starting point and baseline-linked plan; four widths. Mock APIs/fake microphone.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
