const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});const page=await browser.newPage({viewport:{width:390,height:844},permissions:['microphone']});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const state={introduction:'skipped',profile:{name:'',strengths:'',workingOn:'',intention:'',situations:'',focus:'',coachingStyle:'gentle',voicePreset:'default'},attempts:[],messages:[],scenarios:[],completed:[],discovery:{turns:[]},memory:{status:'off'},capabilities:{mode:'live',gemini:true,speech:true,transcription:true,voices:['default'],database:'local',memory:false}};let fail=false;const requests=[];
await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/api/personal-voice')return route.fulfill({json:null});if(path==='/api/state')return route.fulfill({json:state});if(path==='/api/attempts'){
 const req=route.request();const form=await new Response(req.postDataBuffer(),{headers:{'Content-Type':req.headers()['content-type']}}).formData();
 assert.equal(form.get('discoveryId'),state.discovery.turns.at(-1).id);assert.ok(form.get('audio').size>100);
 const attempt={id:form.get('requestId'),discoveryId:form.get('discoveryId'),kind:'delivery',goal:form.get('goal'),context:form.get('context'),transcript:'Hey, good to meet you.',input:'audio',words:[],source:'gemini',createdAt:new Date().toISOString(),feedback:{summary:'Fixture coaching.',strength:null,observation:null,adjustment:'Give the greeting room to land.',example:'',nextPrompt:''}};state.attempts.push(attempt);return route.fulfill({json:attempt});
 }if(path==='/api/discovery'){const b=route.request().postDataJSON();requests.push(b);if(fail)return route.fulfill({status:429,json:{error:'Gemini limit reached.'}});const turn={id:b.requestId,message:b.message,plan:{reply:state.discovery.turns.length?'Let’s make that less formal.':'Let’s keep your energy and land the greeting.',goal:'An approachable introduction',sentence:state.discovery.turns.length?'Hey, good to meet you.':'Hello, it is good to meet you.',cue:'Give the greeting space.',emotion:'warm',intensity:'natural'}};state.discovery.turns.push(turn);return route.fulfill({json:turn});}return route.fulfill({status:503,json:{error:'Disabled during test'}});});
try{await page.goto('http://127.0.0.1:3000');await page.getByRole('navigation').getByRole('button',{name:'Yoro',exact:true}).click();assert.equal(await page.locator('main select').count(),0);
await page.getByLabel('Tell Yoro what you have in mind').fill('I want to sound confident without sounding dismissive');await page.getByRole('button',{name:'Send'}).click();await page.locator('.companion-reply').filter({hasText:'Let’s keep your energy and land the greeting.'}).waitFor();
await page.getByLabel('Keep talking with Yoro').fill('Make it less formal');await page.getByRole('button',{name:'Send'}).click();await page.getByText('Hey, good to meet you.',{exact:true}).waitFor();
await page.reload();await page.getByRole('navigation').getByRole('button',{name:'Yoro',exact:true}).click();await page.locator('.companion-you').filter({hasText:'Make it less formal'}).waitFor();
await page.getByRole('button',{name:'Try it in my voice',exact:false}).click();await page.getByRole('button',{name:'Record response',exact:true}).waitFor();assert.ok(await page.getByRole('button',{name:'Get coaching',exact:true}).isDisabled());assert.equal(await page.locator('.delivery-companion').getByLabel('How do you want to come across?',{exact:true}).count(),0);
await page.getByRole('button',{name:'Record response',exact:true}).click();await page.getByRole('button',{name:/Stop recording/}).waitFor();await page.waitForTimeout(900);await page.getByRole('button',{name:/Stop recording/}).click();await page.getByLabel('Your recorded response',{exact:true}).waitFor();await page.getByRole('button',{name:'Get coaching',exact:true}).click();await page.getByText('Fixture coaching.',{exact:true}).waitFor();await page.getByRole('button',{name:'Back to our conversation',exact:false}).click();await page.locator('.practice-return').getByText('Next time: Give the greeting room to land.',{exact:true}).waitFor();
fail=true;await page.getByLabel('Keep talking with Yoro').fill('More like a quiet conversation');await page.getByRole('button',{name:'Send'}).click();await page.getByRole('alert').filter({hasText:'Gemini limit reached'}).waitFor();assert.equal(await page.getByLabel('Keep talking with Yoro').inputValue(),'More like a quiet conversation');
await page.getByRole('button',{name:'Try a starter introduction',exact:true}).click();await page.getByText('STARTER EXERCISE · NOT PERSONALIZED',{exact:true}).waitFor();
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);}
await page.setViewportSize({width:390,height:844});fs.mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/companion-mobile.png',fullPage:true,animations:'disabled'});assert.deepEqual(errors,[]);assert.equal(requests.length,3);console.log('PASS companion: natural-language refinement, saved conversation reload, no emotion selectors, integrated recording, quota recovery with retained draft, labeled starter, responsive widths.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
