'use client';
import {useRef,useState,type ReactNode} from 'react';
import {planProgress,stageNames,type LearningPlan} from '@/lib/learning-plan';
import type {Attempt,Profile} from '@/lib/domain';
import {Listener,Icon} from './Brand';
import {PendingCoach} from './CoachFeedback';
import StartingPoint from './StartingPoint';
import LessonExample from './LessonExample';
export default function LearningJourney({activePlanId,plans,attempts,profile,refresh,practice,talk,quick,live}:{activePlanId?:string;plans:LearningPlan[];attempts:Attempt[];profile:Profile;refresh:()=>Promise<void>;practice:(plan:LearningPlan,index:number)=>ReactNode;talk:()=>void;quick:()=>void;live:boolean}){
 const plan=plans.find(p=>p.id===activePlanId)||plans.at(-1);const [editing,setEditing]=useState(false),[task,setTask]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<number|null>(null),[started,setStarted]=useState(false);const id=useRef('');const [baseline,setBaseline]=useState<Attempt|null>(null);const [baselineBusy,setBaselineBusy]=useState(false);
 const progress=plan?planProgress(plan,attempts):null;const index=selected??Math.min(progress?.unlocked||0,3);const step=plan?.steps[index];
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');id.current ||= crypto.randomUUID();try{const r=await fetch('/api/learning-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:id.current,task,baselineId:baseline?.id})});const value=await r.json();if(!r.ok)throw Error(value.error||'Your plan could not be prepared.');await refresh();setEditing(false);setSelected(0);setStarted(false);id.current='';}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="learning-journey" aria-label="Your preparation plan">
 {(!plan||editing)?<div className="plan-create"><div className="plan-intro"><div><span className="eyebrow">A REAL MOMENT. A CLEAR PATH.</span><h2>What are you preparing for?</h2><p>Tell me who you’ll be speaking to and what you want them to understand. We’ll build up to it, one challenge at a time.</p></div><Listener state={busy?'thinking':'ready'} priority/></div><form onSubmit={create}><label htmlFor="preparation-task">Your upcoming conversation or presentation</label><textarea id="preparation-task" rows={3} value={task} maxLength={1000} disabled={busy||baselineBusy} onChange={e=>{setTask(e.target.value);setBaseline(null);id.current='';}} placeholder="I’m presenting Yoro at an expo. I want a clear opening, a convincing explanation, and practice answering difficult questions."/><StartingPoint key={task} task={task} onBusy={setBaselineBusy} disabled={busy||!live} onReady={a=>{setBaseline(a);void refresh().catch(e=>setError((e as Error).message));}}/><button className="primary" disabled={busy||baselineBusy||!live||!task.trim()}>Build my practice plan <Icon name="arrow" size={17}/></button>{editing&&<button type="button" disabled={busy} onClick={()=>setEditing(false)}>Keep my current plan</button>}</form>{!live&&<p>Personal plans need live coaching. Quick practice is available below.</p>}{busy&&<PendingCoach label="I’m connecting each challenge to your goal…"/>}</div>:<>
 <header className="plan-intro"><div><span className="eyebrow">YOUR PREPARATION PLAN</span><h2>{plan.title}</h2><p>{plan.task}</p><small>Working toward: {plan.outcome}</small></div><Listener state={progress?.finished?'celebrate':'ready'} priority/></header>
 {plan.baselineId&&<p className="notice">Built with your starting recording. Your lesson targets can evolve as you practice.</p>}<div className="plan-progress"><span>{progress?.unlocked} of 4 practice cycles completed</span><progress value={progress?.unlocked} max={4} aria-label="Completed practice cycles"/></div>
 <ol className="plan-path" aria-label="Your preparation steps">{plan.steps.map((s,i)=><li key={i}><button disabled={i>(progress?.unlocked||0)} aria-current={i===index?'step':undefined} onClick={()=>{setSelected(i);setStarted(false);}}><span className="plan-marker">{progress?.complete[i]?'✓':i+1}</span><span><small>{stageNames[i]}</small><strong>{s.title}</strong>{i>(progress?.unlocked||0)&&<small>After the previous practice</small>}</span></button></li>)}</ol>
 {step&&<article className="plan-step" key={plan.id+index}><span className="eyebrow">STEP {index+1} · {stageNames[index]}</span><h3>{step.title}</h3><p>{step.purpose}</p><div className="plan-challenge"><strong>Your challenge</strong><p>{step.challenge}</p></div><blockquote className="lesson-sentence">{step.sentence}</blockquote><p>{step.cue}</p><small>{index===3?'Use this as a scaffold. Rehearse in your own words and use your real details.':'An example to help you start. Adapt details to your real situation.'}</small><LessonExample text={step.sentence} emotion={step.emotion} preset={profile.voicePreset} direction={step.direction}/>
 {!started?<button className="primary" onClick={()=>setStarted(true)}>{attempts.some(a=>a.planId===plan.id&&a.planStep===index)?'Resume this practice':'Practice this step'} <Icon name="mic" size={17}/></button>:practice(plan,index)}
 <div className="plan-check"><strong>After you listen back</strong><p>{step.successCheck}</p><small>Record, try one adjustment, then reflect on the two takes. That completes this step; it isn’t a claim of mastery.</small></div>
 {progress?.complete[index]&&<div className="plan-complete"><strong>{index===3?'You’ve rehearsed the full path.':'Practice cycle complete.'}</strong><p>{index===3?'Take the skills into your real conversation. You can revisit any step or prepare for another moment.':'Keep what worked as the challenge gets more demanding.'}</p>{index<3&&<button className="primary" onClick={()=>{setSelected(index+1);setStarted(false);}}>Continue to step {index+2} <Icon name="arrow" size={17}/></button>}</div>}
 </article>}
 <div className="row"><button className="text-button" onClick={talk}>Talk this through with Yoro <Icon name="chat" size={17}/></button><button className="text-button" onClick={()=>{setTask(plan.task);setEditing(true);}}>Prepare for a different moment</button></div>
 </>}{plans.length>1&&<nav className="plan-history" aria-label="Your saved plans"><strong>Return to a goal</strong>{plans.map(p=><button key={p.id} aria-pressed={p.id===plan?.id} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/learning-plan/select',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id})});if(!r.ok)throw Error('Could not switch plans.');await refresh();setSelected(null);setStarted(false);setEditing(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{p.title}</button>)}</nav>}{error&&<p className="notice error" role="alert">{error}</p>}<button className="text-button quick-practice-link" onClick={quick}>Just want a quick practice?</button></section>;
}
