'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import Recorder,{type Recording} from './Recorder';
import {Listener} from './Brand';
import {PendingCoach} from './CoachFeedback';
import PersonalExample from './PersonalExample';
import {enrollmentScript,auditionText,type PersonalVoiceView} from '@/lib/personal-voice';
import {inspectVoiceSample} from '@/lib/voice-sample';
import type {Profile} from '@/lib/domain';
import type {DeliveryPlan,DiscoveryTurn} from '@/lib/discovery';

async function enrollmentWav(recording:Recording){
 const context=new AudioContext();let decoded:AudioBuffer;try{decoded=await context.decodeAudioData(await recording.blob.arrayBuffer());}finally{await context.close();}
 if(decoded.duration<60||decoded.duration>150)throw Error('Record 60–150 seconds. About 90 seconds is a good starting point.');
 const offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*24000),24000);const source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const pcm=(await offline.startRendering()).getChannelData(0);
 const bytes=new ArrayBuffer(44+pcm.length*2);const v=new DataView(bytes);const word=(offset:number,value:string)=>{for(let i=0;i<value.length;i++)v.setUint8(offset+i,value.charCodeAt(i));};word(0,'RIFF');v.setUint32(4,bytes.byteLength-8,true);word(8,'WAVE');word(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,24000,true);v.setUint32(28,48000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);word(36,'data');v.setUint32(40,pcm.length*2,true);for(let i=0;i<pcm.length;i++)v.setInt16(44+i*2,Math.round(Math.max(-1,Math.min(1,pcm[i]))*(pcm[i]<0?32768:32767)),true);
 inspectVoiceSample(bytes);return new Blob([bytes],{type:'audio/wav'});
}
export default function PersonalVoiceSetup({profile,practice}:{profile:Profile;practice?:(plan:DeliveryPlan,id:string)=>ReactNode}){
 const [voice,setVoice]=useState<PersonalVoiceView>(null),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[recording,setRecording]=useState<Recording|null>(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[mic,setMic]=useState(false),[error,setError]=useState(''),[url,setUrl]=useState(''),[heard,setHeard]=useState(false),[confirmDelete,setConfirmDelete]=useState(false);
 const [wish,setWish]=useState(profile.intention||'Clear and direct, while staying approachable'),[line,setLine]=useState('I would love to hear about your work. What brought you to this project?'),[target,setTarget]=useState<DiscoveryTurn|null>(null),[rehearse,setRehearse]=useState(false);
 const id=useRef(''),targetId=useRef(''),player=useRef<HTMLAudioElement>(null);useEffect(()=>{void load();},[]);useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]);
 async function load(){try{const r=await fetch('/api/personal-voice');if(!r.ok)throw Error('Personal voice setup is unavailable right now.');setVoice(await r.json());}catch(e){setError((e as Error).message);}finally{setLoaded(true);}}
 async function action(path:string,body:unknown={},method='POST'){const r=await fetch('/api/personal-voice'+path,{method,headers:{'Content-Type':'application/json'},body:method==='DELETE'?undefined:JSON.stringify(body)});if(!r.ok)throw Error((await r.json()).error||'This could not be completed.');return r;}
 async function create(){setBusy(true);setError('');try{
  if(!recording)return;const wav=await enrollmentWav(recording);id.current ||= crypto.randomUUID();
  const status=await fetch('/api/state');if(!status.ok)throw Error('Could not check your connection. Please try again.');
  const chunked=(await status.json()).capabilities?.chunkedVoiceUpload===true;
  if(chunked){const size=2500000,total=Math.ceil(wav.size/size);for(let index=0;index<total;index++){
   const part=new FormData();part.set('requestId',id.current);part.set('consent',String(consent));part.set('index',String(index));part.set('total',String(total));part.set('audio',wav.slice(index*size,(index+1)*size),'sample.part');
   const sent=await fetch('/api/personal-voice/upload',{method:'POST',body:part});if(!sent.ok)throw Error((await sent.json()).error||'Sample upload interrupted. Please try again.');
  }}
  const form=new FormData();form.set('requestId',id.current);form.set('consent',String(consent));if(chunked)form.set('chunked','true');else form.set('audio',wav,'my-voice.wav');
  const r=await fetch('/api/personal-voice',{method:'POST',body:form});const value=await r.json();if(!r.ok)throw Error(value.error||'Setup could not be completed.');setVoice(value);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function audition(){setBusy(true);setError('');try{if(url){await player.current?.play();return;}const r=await action('/audition');setUrl(URL.createObjectURL(await r.blob()));await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function accept(){setBusy(true);setError('');try{setVoice(await(await action('/accept',{accept:true})).json());}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);setError('');try{await action('',{},'DELETE');setVoice(null);setUrl('');setHeard(false);setConsent(false);setRecording(null);setTarget(null);setConfirmDelete(false);id.current='';}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function recover(){setBusy(true);setError('');try{await action('/recover');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function makeTarget(){setBusy(true);setError('');try{targetId.current ||= crypto.randomUUID();const r=await fetch('/api/discovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:targetId.current,message:'Create one short spoken practice example for this intention: '+wish+'. Use these words as the starting point, preserving the meaning: '+line+'. Include an exercise and a concrete delivery cue. Keep the exercise under 350 characters.'})});const data=await r.json();if(!r.ok)throw Error(data.error||'The target could not be prepared.');if(!data.plan)throw Error('Yoro needs more detail to make an example. Try a specific situation.');setTarget(data);setRehearse(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="personal-voice-setup" aria-label="Personal voice setup"><div className="personal-voice-heading"><Listener state={mic?'listening':busy?'thinking':voice?.status==='ready'?'celebrate':'ready'}/><div><span className="eyebrow">HEAR YOUR POTENTIAL</span><h2>Your voice. A new possibility.</h2><p>Hear a delivery you want to work toward, in a voice that sounds like you.</p></div></div>
 {!open&&!voice&&<button type="button" className="primary" disabled={!loaded} onClick={()=>setOpen(true)}>Set up my personal voice</button>}
 {(open||voice)&&<>
 {!voice&&<><p>Record 60–150 seconds in a quiet room. Use your natural accent and a steady, conversational tone. Avoid music, other speakers and exaggerated character voices.</p><blockquote className="enrollment-script">{enrollmentScript}</blockquote><small>Speak naturally. If you finish early, describe a project you enjoy until you reach at least a minute.</small><Recorder key={voice?'saved':'new'} maxSeconds={150} disabled={busy} onRecordingStateChange={setMic} onChange={r=>{setRecording(r);id.current='';}}/><label className="voice-consent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>This is my own voice. I agree to send this sample to ElevenLabs to create a personal voice clone for Yoro. I can delete the clone in this setup.</label><button type="button" className="primary" disabled={busy||mic||!consent||!recording} onClick={()=>void create()}>Create my voice</button><small>We check duration, very low volume and clipping. These checks cannot prove identity, speech clarity, or likeness.</small></>}
 {voice&&(voice.status==='creating'||voice.status==='review')&&<><p>{voice.error||'Your voice setup is being processed. If this takes more than two minutes, check setup.'}</p><button type="button" disabled={busy} onClick={()=>void recover()}>Check setup</button><a href="https://elevenlabs.io/app/voice-lab" target="_blank" rel="noreferrer">Open ElevenLabs Voices ↗</a></>}
 {voice&&(voice.status==='preview'||voice.status==='ready')&&<><span className="eyebrow">{voice.status==='ready'?'YOUR VOICE IS CONNECTED':'FIRST, DOES IT SOUND LIKE YOU?'}</span>{voice.error&&<p>{voice.error}</p>}<p>{auditionText}</p><button type="button" disabled={busy} onClick={()=>void audition()}>Hear my voice preview</button>{url&&<audio ref={player} controls src={url} aria-label="My cloned voice audition" onTimeUpdate={()=>{if((player.current?.currentTime||0)>3)setHeard(true);}} onLoadedData={()=>{void player.current?.play().catch(()=>{});}}/>}<small>AI-generated audition. Listen for your accent, tone and recognizable character. An accurate likeness is not guaranteed.</small>{voice.status==='preview'&&<div className="row"><button type="button" className="primary" disabled={busy||!heard} onClick={()=>void accept()}>That sounds like me</button><button type="button" disabled={busy} onClick={()=>setConfirmDelete(true)}>It doesn’t sound like me</button></div>}</>}
 {voice?.status==='ready'&&practice&&<div className="personal-target"><label htmlFor="personal-wish">How do you want to come across?</label><input id="personal-wish" maxLength={400} value={wish} disabled={busy} onChange={e=>{setWish(e.target.value);targetId.current='';}}/><label htmlFor="personal-line">Something you want to say</label><textarea id="personal-line" rows={2} maxLength={500} value={line} disabled={busy} onChange={e=>{setLine(e.target.value);targetId.current='';}}/><button type="button" className="primary" disabled={busy||!wish.trim()||!line.trim()} onClick={()=>void makeTarget()}>Find my next delivery</button>{target?.plan&&<div className="voice-workshop"><blockquote className="lesson-sentence">{target.plan.sentence}</blockquote><p>{target.plan.cue}</p><PersonalExample key={target.id} text={target.plan.sentence} emotion={target.plan.emotion}/><button type="button" className="text-button" onClick={()=>setRehearse(true)}>Now let me try it</button>{rehearse&&practice(target.plan,target.id)}</div>}</div>}
 {voice&&<div className="personal-voice-delete">{confirmDelete?<><p>Delete your ElevenLabs clone and Yoro’s cached personal examples? Your practice recordings will stay.</p><div className="row"><button type="button" disabled={busy} onClick={()=>void remove()}>Delete my cloned voice</button><button type="button" disabled={busy} onClick={()=>setConfirmDelete(false)}>Keep it</button></div></>:<button type="button" className="text-button" disabled={busy} onClick={()=>setConfirmDelete(true)}>Remove my personal voice</button>}</div>}
 </>}{busy&&<PendingCoach label="I’m preparing your personal voice experience…"/>}{error&&<p className="notice error" role="alert">{error}</p>}<small>Optional. Your usual practice works without a clone. ElevenLabs holds the sample with your clone. Yoro temporarily stores cloud upload pieces, deletes them when assembled, and expires incomplete uploads after 15 minutes.</small></section>;
}
