import KeepComparison from './KeepComparison';
import type { Attempt } from '@/lib/domain';
import { practiceProgress } from '@/lib/practice-moment';
export default function PracticeProgress({ attempts,refresh }: { attempts: Attempt[];refresh:()=>Promise<void> }) {
 const p = practiceProgress(attempts);
 const recent=attempts.filter(a=>a.source==='gemini'&&a.change).slice(-3);const changes=attempts.filter(a=>a.savedComparison||recent.includes(a));
 const labels={closer:'Closer to your goal',steady:'Holding steady',mixed:'Mixed changes',not_yet:'Not closer yet',uncertain:'Inconclusive'};
 return <section className="practice-progress" aria-label="Your practice progress"><span className="eyebrow">THE WORK YOU HAVE PUT IN</span><h2>Your voice, in progress.</h2><div className="progress-numbers"><div><strong>{p.recordings}</strong><span>recordings</span></div><div><strong>{p.lessons}</strong><span>practice cycles</span></div><div><strong>{p.reflections}</strong><span>comparisons reflected on</span></div></div><p>{p.reflections ? `You preferred your retry in ${p.preferredRetry} of ${p.reflections} comparisons. That is your judgment, not an automatic improvement score.` : 'After a retry, choose which delivery fits your intention. Your reflections will appear here.'}</p>{changes.length>0&&<div className="saved-changes"><h3>Saved and recent comparisons</h3>{changes.map(a=><article key={a.id}><strong>{a.change?labels[a.change.outcome]:'Saved comparison'}</strong><p>{a.change?.summary}</p>{a.savedComparison&&<div className="lesson-comparison"><label>Before<audio controls preload="none" src={'/api/audio/'+a.parentId}/></label><label>After<audio controls preload="none" src={'/api/audio/'+a.id}/></label></div>}<KeepComparison id={a.id} kept={!!a.savedComparison} refresh={refresh}/><small>{new Date(a.createdAt).toLocaleDateString()} · AI comparison of two takes</small></article>)}</div>}<small>Practice totals are not skill ratings. Expression scores need further validation.</small></section>;
}
