'use client';
import {useEffect,useRef,useState} from 'react';
import type {ReturnCheck} from '@/lib/domain';
import type {LearningPlan} from '@/lib/learning-plan';
import {dueReturns} from '@/lib/return-habit';
export default function ReturnLoop({items,plan,refresh}:{items:ReturnCheck[];plan?:LearningPlan;refresh:()=>Promise<void>}){
 const [now,setNow]=useState(Date.now()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[enabled,setEnabled]=useState(false);const notifying=useRef(false);
 const due=dueReturns(items,now)[0];const pending=items.find(r=>r.planId===plan?.id&&!r.completedAt);
 async function post(path:string,body:unknown){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Could not save your check-in.');return data;}
 useEffect(()=>{try{setEnabled(localStorage.getItem('yoro-open-reminders')==='yes');}catch{}const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!enabled||!due||due.notifiedAt||notifying.current||!('Notification' in window)||Notification.permission!=='granted')return;notifying.current=true;void post('return-check/notified',{id:due.id}).then(()=>{const n=new Notification('A moment with Yoro',{body:'How did your conversation go? Bring one moment back to practice.',tag:'yoro-return'});n.onclick=()=>{window.focus();n.close();};return refresh();}).catch(()=>{}).finally(()=>{notifying.current=false;});},[due,enabled,refresh]);
 async function act(path:string,body:unknown){setBusy(true);setError('');try{await post(path,body);await refresh();setNote('');setNow(Date.now());}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function notifications(){if(!('Notification'in window)){setError('This browser does not offer notifications. Your check-ins still appear here.');return;}try{const permission=await Notification.requestPermission();const yes=permission==='granted';setEnabled(yes);localStorage.setItem('yoro-open-reminders',yes?'yes':'no');if(!yes)setError('Notifications are off. Your check-ins still appear here.');}catch{setError('Notifications are unavailable here. Your check-ins still appear here.');}}
 if(!plan&&!due)return null;
 return <section className="return-loop plan-step" aria-label="Bring practice into real life"><span className="eyebrow">OUT THERE, IN YOUR OWN VOICE</span><h3>{due?'How did it go?':'Take this into a real conversation.'}</h3>{due?<><p>What you notice outside practice helps shape your next lesson. No streak to lose.</p><label htmlFor="return-note">One moment to remember (optional)</label><textarea id="return-note" value={note} maxLength={600} rows={2} onChange={e=>setNote(e.target.value)} placeholder="My opening felt clear, but I rushed when they asked a question."/><div className="row">{([['helped','It helped'],['mixed','Some parts worked'],['hard','It was difficult'],['not_yet','Haven’t tried yet']]as const).map(([outcome,label])=><button key={outcome} disabled={busy} onClick={()=>void act('return-check/complete',{id:due.id,outcome,note})}>{label}</button>)}</div></>:<><p>Come back with one thing that worked and one moment you want to rehearse.</p>{pending?<p role="status">Check-in: {new Date(pending.dueAt).toLocaleString()}</p>:<div className="row"><button disabled={busy} onClick={()=>void act('return-check',{planId:plan!.id,dueAt:new Date(Date.now()+3*3600000).toISOString()})}>Check in later today</button><button disabled={busy} onClick={()=>void act('return-check',{planId:plan!.id,dueAt:new Date(Date.now()+86400000).toISOString()})}>Check in tomorrow</button></div>}</>}{!enabled?<button className="text-button" onClick={()=>void notifications()}>Enable browser reminders</button>:<button className="text-button" onClick={()=>{setEnabled(false);try{localStorage.removeItem('yoro-open-reminders');}catch{}}}>Turn off browser reminders</button>}<small>Browser reminders work while Yoro is open. If you close it, your check-in will be waiting when you return.</small>{error&&<p role="alert">{error}</p>}</section>;
}
